# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["master"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: client
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Add homepage and deployment scripts to package.json
        run: |
          URL="https://webdesignsbytom.github.io/Cat-App-Website"
          jq ".homepage = \"${URL}\"" package.json > tmp.json && mv tmp.json package.json
          jq '.scripts += {"predeploy": "npm run build", "deploy": "gh-pages -d build"}' package.json > tmp.json && mv tmp.json package.json
        shell: bash
        
      - name: Install dependencies and build (optional)
        run: |
          npm ci
          git remote add origin https://github.com/webdesignsbytom/Cat-App-Website.git
          cat package.json
          npm install gh-pages --save-dev
          CI=false npm run build

      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: List build directory
        run: ls -al ./build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload built files from the 'dist' or 'build' folder
          path: './client/build' # Adjust if your build folder is named differently

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
